name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ericvanjohnson/blog-post-workflow@master
        with:
          feed_list: "https://feeds.simplecast.com/iYRiH9ym,https://medium.com/feed/@ericvanjohnson"
          max_post_count: 5
